// src/server/ai/claude.ts
import Anthropic from '@anthropic-ai/sdk';
import { env } from '~/env';

const anthropic = new Anthropic({
  apiKey: env.ANTHROPIC_API_KEY,
});

export async function simplifyDocument(content: string): Promise<string> {
  const prompt = `
You are an AI assistant specialized in simplifying complex legal documents. Your task is to simplify the following document while maintaining its key points and overall meaning. Please provide a simplified version that is easier to understand for a general audience and highlight key points that a reader may need to know.

Original Document:
${content}

Simplified Version:
`;

  try {
    const msg = await anthropic.messages.create({
      model: "claude-3-5-sonnet-20240620",
      max_tokens: 8192, // Adjust based needs
      messages: [{ role: "user", content: prompt }],
    });

    if (!msg.content || msg.content.length === 0) {
      throw new Error('No content generated by Claude');
    }

    const textContent = msg.content.find(block => block.type === 'text');
    if (!textContent || !('text' in textContent)) {
      throw new Error('No text content found in Claude response');
    }

    return textContent.text;
  } catch (error) {
    console.error('Error simplifying document:', error);
    throw new Error('Failed to simplify document');
  }
}